### ISSUE TITLE
start_date and end_date disappear in promotion admin

### ISSUE THREAD

**Issue by kamontat** [PairMhai/Backend#49]
## What kind of issue? (uncomment at least one)
- [X] Bug

## Explanation
`start_date` and `end_date` should editable in admin page

## Environment
- python: VERSION
- django: VERSION
- django-rest: VERSION
- OS: TYPE,VERSION
- app: VERSION
- other: xxxxxx

**Comment by piromsurang** [comment]
I am finished at a #98
